name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Repositorylarni yuklash
        uses: actions/checkout@v4

      - name: Node versiyasini o‘rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '18' # kerakli versiyani yozing

      - name: node_modulesni yuklab olish
        run: npm install
